# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Calimpio.BitChat
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - BitChat
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/user-attachments/files/28670853/BitChat_v1.0.0.zip
    InstallerSha256: 9b1b674a50d686c8c932cf3a523452b872ea4a1223e31bee2c6f7e4b890fce9b
ManifestType: installer
ManifestVersion: 1.6.0
