# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Calimpio.BitChat
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - BitChat
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/user-attachments/files/28670853/BitChat_v1.0.0.zip
    InstallerSha256: c521fcbe70c54e8c2c92f5533d9a911cf46f0ebc89f35ab8a339922ca4f2f09a
ManifestType: installer
ManifestVersion: 1.6.0
